app/admin_panel/forms.py
from flask_wtf import FlaskForm
from wtforms import IntegerField, StringField, SubmitField, FloatField, SelectField
from wtforms.widgets import TextArea
from wtforms.validators import DataRequired


class CreateNewProject(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    Description = StringField('Description', validators=[DataRequired()])

    create_button = SubmitField('Create')

class EditProjectForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    Description = StringField('Description', validators=[DataRequired()])

    submit = SubmitField('Update')



class CreateNewTask(FlaskForm):
    hit_title = StringField('HIT Title', validators=[DataRequired()])
    hit_desc = StringField('Description', widget=TextArea(), validators=[DataRequired()])
    keywords = StringField('keywords', validators=[DataRequired()], default='survey, feedback, robot control')
    fix_price = FloatField('Fix Price (USD)')
    time_limit = IntegerField('Time limit (in minutes)', validators=[DataRequired()])
    #Qualifications
    country = StringField('Country', validators=[DataRequired()], default="US")
    percent_approved = IntegerField('Percent Approved', validators=[DataRequired()], default=97)
    HITS_approved = IntegerField('# of HITS Approved', validators=[DataRequired()], default=1000)
    task_url = StringField('URL for TASK', validators=[DataRequired()], default = 'https://pepperanywhere.herokuapp.com/task')

    min_active = IntegerField('Min. Number of Active Workers', validators=[DataRequired()], default=2)
    min_waiting = IntegerField('Min. Number of Waiting Workers', validators=[DataRequired()], default=1)
    max_active = IntegerField('Max. Number of Active Workers', validators=[DataRequired()], default=3)
    max_waiting = IntegerField('Max. Number of waiting Workers', validators=[DataRequired()], default=3)


    submit = SubmitField('Create a New Task')


class EditTask(FlaskForm):
    hit_title = StringField('HIT Title', validators=[DataRequired()])
    hit_desc = StringField('Description', widget=TextArea(), validators=[DataRequired()])
    Condition = StringField('Condition', widget=TextArea(), validators=[DataRequired()])
    # language = SelectField(
    #     'Programming Language',
    #     choices=[('cpp', 'C++'), ('py', 'Python'), ('text', 'Plain Text')])
    keywords = StringField('keywords', validators=[DataRequired()], default='survey, feedback, robot control')
    # target_workers = IntegerField('Target Workers', validators=[DataRequired()])
    fix_price = FloatField('Fix Price (USD)', validators=[DataRequired()], default=1.0)
    time_limit = IntegerField('Time limit (in minutes)', validators=[DataRequired()])

    #for production purposes
    # hourly_rate = FloatField('Hourly Rate', validators=[DataRequired()], default=0.0)
    # work_rate = FloatField('Rate per Contribution', validators=[DataRequired()], default=0.0)

    #Qualifications
    country = StringField('Country', validators=[DataRequired()], default="US")
    percent_approved = IntegerField('Percent Approved', validators=[DataRequired()], default=97)
    HITS_approved = IntegerField('# of HITS Approved', validators=[DataRequired()], default=1000)

    # status = StringField('status', validators=[DataRequired()])
    task_url = StringField('URL for TASK', validators=[DataRequired()], default = 'http://127.0.0.1:5000/waiting_task')

    #New fields
    # waiting_time_window = IntegerField('Maximum Time Workers Should Wait before they Leave', validators=[DataRequired()], default=5)
    min_active = IntegerField('Min. Number of Active Workers', validators=[DataRequired()], default=2)
    min_waiting = IntegerField('Min. Number of Waiting Workers', validators=[DataRequired()], default=1)
    max_active = IntegerField('Max. Number of Active Workers', validators=[DataRequired()], default=3)
    max_waiting = IntegerField('Max. Number of waiting Workers', validators=[DataRequired()], default=3)


    submit = SubmitField('Save Changes')

class MigrateWorkers(FlaskForm):
    NumberOfWorkers = IntegerField('Number of Workers to Migrate', validators=[DataRequired()], default=2)
    submit = SubmitField('Migrate')

app/admin_panel/__init__.py
# app/catalog/__init__.py

from flask import Blueprint


main = Blueprint('main', __name__ , template_folder='templates')

from app.admin_panel import routes

app/admin_panel/routes.py
from app.admin_panel import main
from app.Pavilion import Pavilion
from app import db
import datetime
# from app.admin_panel.models import Book, Publication
from app.admin_panel.models import Project, Task
from app.Pavilion.models import LiveStatus, WorkerStatus, Worker, Session, \
                                     DetailedStatus, Assignments, SESSION_SQLALCHEMY

from flask import render_template, flash, request, redirect, url_for, jsonify
from flask import session as login_session
from app.auth import authentication as at
from flask_login import login_required
from flask_login import login_user, logout_user, login_required, current_user
from flask import render_template, request, redirect, url_for, flash # for flash messaging

from app.admin_panel.forms import CreateNewProject, CreateNewTask, EditTask, MigrateWorkers
# from app.admin_panel.forms import EditBookForm, CreateBookForm

from boto.mturk.connection import MTurkConnection
from boto.mturk.question import ExternalQuestion
from boto.mturk.qualification import Qualifications, PercentAssignmentsApprovedRequirement, NumberHitsApprovedRequirement
from boto.mturk.price import Price
from sqlalchemy import exc,asc, desc, and_, or_, cast, Date

from xml.dom.minidom import parseString

from app import connection #Mturk connection object

from app import socketio

@main.route('/')
@login_required
def home():
    projects = Project.query.all()
    return render_template('home.html', projects = projects)

@main.route('/create_project', methods=['GET', 'POST'])
@login_required
def create_project():
    form = CreateNewProject()
    #if data is validate, hten create a new project
    if form.validate_on_submit():
        Project.create_project(
        project_title = form.title.data,
        project_desc = form.Description.data,
        created_by = login_session['id'])

        flash('Project was Created Successfully!')
        return redirect(url_for('main.home'))
    return render_template('create_new_project.html', form = form)

@main.route('/create_task/<project_id>', methods=['GET', 'POST'])
@login_required
def create_task(project_id):
    form = CreateNewTask()
    if form.validate_on_submit():
        task = Task(project_id, "Not Active", form.hit_title.data, form.hit_desc.data,
                    form.keywords.data, form.fix_price.data, form.time_limit.data*60, form.country.data, form.percent_approved.data,
                     form.HITS_approved.data, form.task_url.data, form.min_active.data,
                     form.min_waiting.data, form.max_active.data, form.max_waiting.data, datetime.datetime.utcnow())

        db.session.add(task)
        db.session.commit()

        flash('Task was Created Successfully!')
        return redirect(url_for('main.home'))
    return render_template('create_new_task.html', form = form)

@main.route('/list_tasks/<project_id>', methods=['GET', 'POST'])
@login_required
def list_tasks(project_id):
    tasks = db.session.query(Task).filter(Task.p_id==project_id).order_by(Task.id).all()
    return render_template('task_list.html', tasks = tasks)

@main.route('/post_task/<task_id>', methods=['GET', 'POST'])
@login_required
def postTask(task_id):

    task = db.session.query(Task).filter(Task.id==task_id).first()
    # taskinfo_session['task_id'] = task_id   #to retrieve task_id on the waiting room
    if task.task_status == "Active":
        flash('This Task is already Live!')
        return redirect(url_for('main.list_tasks', project_id=task.p_id))
    else:

        #frame_height in pixels
        frame_height = 800
        #This url will be the url of your application, with appropriate GET parameters
        url = task.task_url
        questionform = ExternalQuestion(url, frame_height).get_as_xml()
        create_hit_result = connection.create_hit(
            Title=task.title,
            Description=task.Description,
            Keywords=task.keywords,
            AssignmentDurationInSeconds = task.time_limit,
            MaxAssignments=task.max_active + task.max_waiting,
            Question=questionform,
            Reward=str(task.fix_price),
            LifetimeInSeconds = 60*60,
            AutoApprovalDelayInSeconds=60*60*72,
            QualificationRequirements=[
                    { 'QualificationTypeId': '000000000000000000L0',
                        'Comparator': 'GreaterThanOrEqualTo',
                        'IntegerValues': [task.approval_rate]
                    },
                    { 'QualificationTypeId': '00000000000000000040',
                        'Comparator': 'GreaterThanOrEqualTo',
                        'IntegerValues': [task.number_of_HITS]
                    },

                    { 'QualificationTypeId': '00000000000000000071',
                        'Comparator': 'In',
                        'LocaleValues':[{'Country':task.country}]
                        # 'LocaleValues':[{'Country':'US'}, {'Country':'IN'}]
                    }
                    ]
                )
            #https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_QualificationRequirementDataStructureArticle.html#ApiReference_QualificationType-IDs
            # print(create_hit_result[0])
        flash('Task was posted Successfully to AMT!')
        # hit. = create_hit_result[0].HITTypeId
        task.HIT_Type_id = create_hit_result['HIT']['HITTypeId']
        task.task_status = "Active"
        session = Session(task.id, datetime.datetime.utcnow(), "Live")
        db.session.add(session)

        #need to hire workers automatically?
        server_session = SESSION_SQLALCHEMY.query.filter_by(id=2).first()
        server_session.Name = 'yes'

        #this variable was set to avoid premature moving of workers from waiting to active queue
        server_session = SESSION_SQLALCHEMY.query.filter_by(id=3).first()
        server_session.Name = 'not met'

        db.session.commit()


        # Simple Notification Service registration
        connection.update_notification_settings(
        HITTypeId = create_hit_result['HIT']['HITTypeId'],
        Notification = {
         'Destination': 'YOUR_TOPIC_ON_AMAZON_SNS',
         'Transport':'SNS',
         'Version':'2014-08-15',
         'EventTypes':['AssignmentAbandoned', 'AssignmentReturned',
                        'HITCreated', 'HITExpired'] })

        return redirect(url_for('main.list_tasks', project_id=task.p_id))


@main.route('/cloning/<task_id>/<project_id>', methods=['GET', 'POST'])
@login_required
def cloning(task_id, project_id):
    error_occured = False
    try:
        task = Task.query.filter(and_(Task.id==task_id, Task.p_id==project_id)).first()

        task = Task(project_id, "Not Active", task.title, task.Description,
                    task.keywords, task.fix_price, task.time_limit,task.country, task.approval_rate,
                    task.number_of_HITS, task.task_url, task.min_active,
                    task.min_waiting, task.max_active, task.max_waiting, datetime.datetime.utcnow())

        db.session.add(task)
        db.session.commit()


    except:
        flash('Cloning was not successful!')
        error_occured = True
    if not error_occured:
        flash('Cloning was successful!')
    return redirect(url_for('main.list_tasks', project_id=task.p_id))


@main.route('/edit/<project_id>/<task_id>', methods=['GET', 'POST'])
@login_required
def edit_task(project_id, task_id):
    task = Task.query.get(task_id)
    form = EditTask(obj=task)
    if request.method == 'GET':
        form.hit_title.data = task.title
        form.hit_desc.data = task.Description
        form.keywords.data = task.keywords
        form.fix_price.data = task.fix_price
        form.time_limit.data = int(task.time_limit / 60)
        form.country.data  = task.country
        form.percent_approved.data = task.approval_rate
        form.HITS_approved.data = task.number_of_HITS
        form.task_url.data = task.task_url
        form.min_active.data = task.min_active
        form.min_waiting.data = task.min_waiting
        form.max_active.data = task.max_active
        form.max_waiting.data = task.max_waiting
    if form.validate_on_submit():
        task.title = form.hit_title.data
        task.Description = form.hit_desc.data
        task.keywords = form.keywords.data
        task.fix_price = form.fix_price.data
        task.time_limit = form.time_limit.data*60
        task.country =  form.country.data
        task.approval_rate = form.percent_approved.data
        task.number_of_HITS = form.HITS_approved.data
        task.task_url = form.task_url.data
        task.min_active = form.min_active.data
        task.min_waiting = form.min_waiting.data
        task.max_active = form.max_active.data
        task.max_waiting = form.max_waiting.data
        db.session.add(task)
        db.session.commit()
        flash('Task Edited Successfully')
        return redirect(url_for('main.list_tasks', project_id=task.p_id))
    return render_template('edit_task.html', form=form)

@main.route('/migrate/<project_id>/<task_id>', methods=['GET', 'POST'])
@login_required
def migrate_workers(project_id, task_id):

    form = MigrateWorkers()

    if form.validate_on_submit():

        #update the starting condition.
        server_session = SESSION_SQLALCHEMY.query.filter_by(id=3).first()
        server_session.Name = 'met'
        db.session.commit()

        #fetch latest workers
        workers = LiveStatus.query.filter_by(status_id=1).order_by(asc(LiveStatus.time_stamp)).all()

        workers_list = []
        count = 0
        for worker_status in workers:

            if count >= form.NumberOfWorkers.data:
                break

            #change status of workers from 'waiting' to 'active'
            worker_status.status_id = 2
            w_ids = Worker.query.filter_by(id=worker_status.w_id).first()

            #append workers to list (this was done to send message to only specific/active clients)
            workers_list.append(w_ids.AMT_worker_id)

app/admin_panel/templates/create_new_project.html
{% extends 'layout.html' %}
{% block content %}



<div class="container">
    <h4 style="margin-left: 45px"> create a new Project </h4>
    <hr>
      {{ form.hidden_tag() }}
      {{ wtf.quick_form(form) }}
</div>

{% endblock %}

app/admin_panel/templates/create_new_task.html
{% extends 'layout.html' %}
{% block content %}

<div class="container">
    <h4 style="margin-left: 45px"> create a new Task </h4>
    <hr>
      {{ form.hidden_tag() }}
      {{ wtf.quick_form(form) }}
</div>

{% endblock %}

app/admin_panel/templates/edit_task.html
{% extends 'layout.html' %}
{% block content %}



<div class="container">
    <h4 style="margin-left: 45px"> Edit a Task</h4>
    <hr>
      {{ form.hidden_tag() }}
      {{ wtf.quick_form(form) }}
</div>

{% endblock %}

app/admin_panel/templates/home.html
{% extends 'layout.html' %}
{% block content %}

<div class="container projects">
      <div class="row">
          {% for project in projects %}
          <div class="col-md-4">
          <h4>Title: {{project.project_title}}</h4>
          <p>Desc: {{project.project_desc}}</p>
          <p>Date Created: {{project.date_created}}</p>
          <p> <a href="{{ url_for('main.create_task', project_id = project.id)}}">Create New Task</a> </p>
          <p> <a href="{{ url_for('main.list_tasks', project_id = project.id)}}">See Tasks</a> </p>
      </div>
          {% endfor %}
  </div>

{% endblock %}

app/admin_panel/templates/layout.html
{% import "bootstrap/wtf.html" as wtf %}

<!DOCTYPE html>
<html lang="en">

    {# head #}
    {% block head %}
        <head>
          <title> Perry CC </title>
          <meta charset="utf-8">
          <meta http-equiv="X-UA-Compatible" content="IE=edge">
          <meta name="viewport" content="width=device-width, initial-scale = 1">

          <title>Crowd Task Interface</title>

          <!-- Bootstrap CSS -->
          <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}">

          <!--  Google fonts-->
          <link href="https://fonts.googleapis.com/css?family=Sansita" rel="stylesheet" >

          <!-- General CSS -->
          <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}" >

          <!-- JS for SocketIO -->
          <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.min.js"></script>
          <!-- JQuery -->
          <script type="text/javascript" src="{{url_for('static', filename='js/jquery.js')}}"></script>

        </head>
    {% endblock head %}

    {# body #}
    {% block body %}
    <body>
    <div class="wrapper">
        {# navigation bar #}
        {% block navbar %}
            <nav class="navbar navbar-inverse">
                <div class="container">
                    <a class="navbar navbar-text" href="{{ url_for('main.home') }}">
                        <h3 class="title"> Perry Crowd Control </h3>
                    </a>
                    <ul class="nav navbar-nav pull-right">
                        <li><a href="{{ url_for('main.home') }}"> Home </a></li>
                        <!-- <li><a href="{{ url_for('authentication.register_user') }}"> Register </a></li> -->
                        <li> {% if current_user.is_authenticated %}
                                <a href="{{ url_for('authentication.log_out_user') }}"> SignOut </a>
                             {% else %}
                                <a href="{{ url_for('authentication.do_the_login') }}"> SignIn </a>
                             {% endif %}
                        </li>
                        <li>
                            <a href="#">
                                {% if current_user.is_authenticated %}
                                    Logged-In as <b style="color: deeppink"> {{ current_user.user_name.title() }} </b>
                                {% else %}
                                    Not Logged-In
                                {% endif %}
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
        {% endblock navbar %}

        {# flash messaging #}
        {% for message in get_flashed_messages() %}
                <div class=" container alert alert-info">
                    <button type="button" class="close" data-dismiss="alert"></button>
                    {{ message }}
                </div>
        {% endfor %}

        {# empty block for custom content #}
        {% block content %} {% endblock content %}

        {# footer #}
        {% block footer %}
            <footer>
                <div class="container ftr">
                    <hr>
                    <p class="text-center small">Perry Crowd Control &copy;  |  2018</p>
                </div>
            </footer>
        {% endblock footer %}

    </div>
    </body>
    {% endblock body %}
</html>

app/admin_panel/templates/migrate_workers.html
{% extends 'layout.html' %}
{% block content %}



<div class="container">
    <h4 style="margin-left: 45px"> Migrate Workers</h4>
    <hr>
      {{ form.hidden_tag() }}
      {{ wtf.quick_form(form) }}
</div>

{% endblock %}

app/admin_panel/templates/task_list.html
{% extends 'layout.html' %}
{% block content %}

        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Task ID</th>
                    <th scope="col">Project ID</th>
                    <th scope="col">Title</th>
                    <th scope="col">Target Workers</th>
                    <th scope="col">Time Limit</th>
                    <th scope="col">Date Created</th>
                    <th scope="col">Status</th>
                    <th scope="col">Create Copy of this task</th>
                    <th scope="col">Migrate</th>
                    <th scope="col">Operations</th>
                    <th scope="col">Post to MTUrk</th>
                    <th scope="col">Stop</th>
                    <th scope="col">Expire</th>
                </tr>
            </thead>
            <tbody>
            {% for task in tasks %}
                <tr>
                    <td> {{task.id }} </td>
                    <td> {{task.p_id }} </td>
                    <td> {{ task.title }} </td>
                    <td> {{ task.max_active + task.max_waiting}} </td>
                    <td> {{task.time_limit / 60 }} min.</td>
                    <td> {{ task.date_created }} </td>
                    <td> {{ task.task_status }} </td>
                    <td> <a href="{{ url_for('main.cloning', task_id=task.id, project_id=task.p_id) }}"> Clone it </a></td>
                    <td> <a href="{{ url_for('main.migrate_workers', task_id=task.id, project_id=task.p_id) }}"> Migrate Workers </a></td>
                    <td>
                      <a href="#">Delete</a> |
                      <a href="{{ url_for('main.edit_task', task_id=task.id, project_id=task.p_id) }}">Edit</a>
                    </td>
                    <td> <a href="{{ url_for('main.postTask', task_id=task.id) }}"> POST </a></td>
                    <td><button type="button" class="btn btn-primary" onclick="stop_task();">STOP</button></td>
                    <td><button type="button" class="btn btn-primary" onclick="expireHIT({{task.id}});">Expire HIT</button></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <script type="text/javascript" src="{{url_for('static', filename='js/admin_tasks.js')}}"></script>
{% endblock %}